Facebook_API/urls.py
from django.urls import path

from Facebook_API import views

urlpatterns = [

    path(
        route='login/',
        view=views.Login.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.Logout,
        name='logout'
    ),
    path(
        route='inicio/',
        view=views.Index.as_view(),
        name='inicio'
    ),
    path(
        route='home/',
        view=views.userDetails,
        name='home'
    ),
    path(
        route='getForms/',
        view=views.ListForms,
        name='getForms'
    ),
    path(
        route='admin/',
        view=views.Admin.as_view(),
        name='admin'
    ), path(
        route='csvdata/',
        view=views.GoogleData,
        name='csvdata'
    ),
    path(
        route='newForm/',
        view=views.InsertarFormulario,
        name='newForm'
    ),
    path(
        route='campañas/',
        view=views.Campañas.as_view(),
        name='campañas'
    ),
    path(
        route='resultados/',
        view=views.GoogleResults.as_view(),
        name='resultados'
    ),
    path(
        route='facebookUsers/',
        view=views.FacebookUser.as_view(),
        name='facebookUsers'
    ),
    path(
        route='inhabilitarFormulario/',
        view=views.InhabilitarFormulario,
        name='inhabilitarFormulario'
    ),

]

HabitatYConstruccion/urls.py
"""HabitatYConstruccion URL Configuration"""
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
                  path('api/', include(('Facebook_API.urls', 'api'), namespace='api')),
                  path('social-auth/', include('social_django.urls', namespace='social'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/navbar/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Hábitat y Construcción</a>

    {% if user.is_authenticated %}

        <div class="ml-auto">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'api:facebookUsers' %}">Facebook API</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'api:resultados' %}">Resultados</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'api:admin' %}">Registrar formularios</a>
                </li>
                &nbsp;
                <li class="nav-item">
                    <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'api:logout' %}"><i
                            class="fa fa-sign-out"></i></a>
                </li>
            </ul>
        </div>
    {% else %}

        <div class="ml-auto">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="btn btn-outline-info" href="{% url 'api:login' %}">Login</a>
                </li>
            </ul>
        </div>

    {% endif %}

</nav>