Facebook_API/urls.py
from django.urls import path

from Facebook_API import views

urlpatterns = [

    path(
        route='login/',
        view=views.Login.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.Logout,
        name='logout'
    ),
    path(
        route='inicio/',
        view=views.Index.as_view(),
        name='inicio'
    ),
    path(
        route='home/',
        view=views.userDetails,
        name='home'
    ),
    path(
        route='getForms/',
        view=views.ListForms,
        name='getForms'
    ),
    path(
        route='admin/',
        view=views.Admin.as_view(),
        name='admin'
    ), path(
        route='csvdata/',
        view=views.GoogleData,
        name='csvdata'
    ),
    path(
        route='newForm/',
        view=views.InsertarFormulario,
        name='newForm'
    ),
    path(
        route='campañas/',
        view=views.Campañas.as_view(),
        name='campañas'
    ),
    path(
        route='resultados/',
        view=views.GoogleResults.as_view(),
        name='resultados'
    ),
    path(
        route='facebookUsers/',
        view=views.FacebookUser.as_view(),
        name='facebookUsers'
    ),
    path(
        route='inhabilitarFormulario/',
        view=views.InhabilitarFormulario,
        name='inhabilitarFormulario'
    ),

]

HabitatYConstruccion/urls.py
"""HabitatYConstruccion URL Configuration"""
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
                  path('api/', include(('Facebook_API.urls', 'api'), namespace='api')),
                  path('social-auth/', include('social_django.urls', namespace='social'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/FacebookUser.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>H&B</title>
    <link rel="stylesheet" href="{% static 'bootstrap/darkly/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'scripts/notifications/notifications.css' %}">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <script src="{% static 'scripts/notifications/notifications.js' %}"></script>
</head>
<body>
{% include 'navbar/navbar.html' %}

<div class="d-flex justify-content-center mt-3 pa-5 ">
    <div id="overflow_table">
        <div class="card card-lg text-white bg-secondary mb-3 w-80" style="max-width: 80rem;">
            <div class="card-header">
                <h3>
                    Usuarios de Facebook
                </h3>
            </div>

            <div class="card-body">

                <table class="table table-responsive-lg" id="table_id">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Foto Perfil</th>
                        <th scope="col">Email</th>
                        <th scope="col">Nombre Usuario</th>
                        <th scope="col">Genero</th>
                        <th scope="col">Rango de Edad</th>
                        <th scope="col">Tipo de Baldosa</th>
                        <th scope="col">Tipo Salpicadero</th>
                        <th scope="col">Tipo de Baño</th>
                        <th scope="col">Tipo de Sala</th>
                    </tr>
                    </thead>
                    <!--Registros de la tabla-->

                    <tbody id="results">

                    {% if object_list %}
                        {% for fb in object_list %}

                            <tr>
                                <td>
                                    <img src="{{ fb.Usuario.picture }}" alt="">
                                </td>
                                <td>
                                    {{ fb.Usuario.email }}
                                </td>
                                <td>
                                    {{ fb.Usuario.name }}
                                </td>
                                <td>
                                    {{ fb.genero }}
                                </td>
                                <td>
                                    {{ fb.edad }}
                                </td>
                                <td>
                                    {{ fb.Tipo_baldosa }}
                                </td>
                                <td>
                                    {{ fb.Tipo_Salpicadero }}
                                </td>
                                <td>
                                    {{ fb.Tipo_Baño }}
                                </td>
                                <td>
                                    {{ fb.Tipo_Sala }}
                                </td>

                            </tr>

                        {% endfor %}
                    {% else %}
                        <div class="alert alert-dismissible alert-primary">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <strong>Atención!</strong> Lista Vacia
                        </div>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</body>

<script src="{% static 'scripts/jquery/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

</html>

templates/Resultados.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>H&B</title>
    <link rel="stylesheet" href="{% static 'bootstrap/darkly/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'scripts/notifications/notifications.css' %}">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <script src="{% static 'scripts/notifications/notifications.js' %}"></script>
</head>
<body>
{% include 'navbar/navbar.html' %}

<div class="d-flex justify-content-center mt-3 pa-5 ">
    <div class="card text-white bg-secondary mb-3 w-50" style="max-width: 60rem;">
        <div class="card-header">
            <h3>
                Resultados
            </h3>
        </div>
        <div class="card-body">
            <table class="table" id="table_id">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Nombre Campaña</th>
                    <th scope="col">Resultados</th>
                    <th scope="col">Acciones</th>
                </tr>
                </thead>
                <!--Registros de la tabla-->
                <tbody id="results">
                {% if formularios_list %}
                    {% for formularios in formularios_list %}
                        <tr>
                            <td>
                                <strong>{{ formularios.nombreFormulario }}</strong>
                            </td>

                            <td>
                                <a href="{{ formularios.urlRespuestas }}" class="btn btn-success btn-lg active"
                                   role="button"
                                   aria-pressed="true" data-toggle="tooltip" data-placement="right"
                                   title="Ver Resultados"><i class="fa fa-table"></i>
                                </a>
                            </td>
                            <td>
                                <button class="btn btn-info btn-lg" id="SaveButton" value="{{ formularios.pk }}"
                                        data-toggle="tooltip" data-placement="right"
                                        title="Guardar resultados">
                                    <i class="fa fa-save"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <div class="alert alert-dismissible alert-primary">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Atención!</strong> Lista Vacia
                    </div>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>

<script src="{% static 'scripts/jquery/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script>


    const SuccessNotification = window.createNotification({
        theme: 'success',
        showDuration: 5000
    });
    let btn = document.getElementById('SaveButton');

    btn.addEventListener('click', _ => {
        event.preventDefault();
        $.ajax({
            type: "POST",
            url: "{% url 'api:getForms' %}",
            data: {
                FormID: btn.value,
                dataType: "json",
                csrfmiddlewaretoken: '{{csrf_token}}'
            },

            success: function (data) {
                SuccessNotification({message: data['message']})
            },
        });

    })

</script>

</html>

templates/admin.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>H&B</title>
    <link rel="stylesheet" href="{% static 'bootstrap/darkly/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'scripts/notifications/notifications.css' %}">
    <script src="{% static 'scripts/notifications/notifications.js' %}"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
{% include 'navbar/navbar.html' %}
<div class="d-flex justify-content-center mt-3 pa-5 ">
    <div class="card text-center w-50">
        <div class="card-header d-flex justify-content-between">
            <h3>
                Campañas
            </h3>

            <button type="button" class="btn btn-primary" id="ButtonModal"
                    data-toggle="modal"
                    data-target="#exampleModal">
                <i class="fa fa-plus"></i>
            </button>
        </div>
        <div class="card-body">

            <div class="col" id="Habilitados">
                <strong>Habilitados</strong>
                <table class="table" id="table_id">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nombre Campaña</th>
                        <th scope="col">Url Formulario</th>
                        <th scope="col">Url Resultados</th>
                        <th scope="col">Acciones</th>
                    </tr>
                    </thead>
                    <!--Registros de la tabla-->
                    <tbody id="results">
                    {% if object_list %}
                        {% for data in object_list %}
                            {% if data.estado %}
                                <tr>
                                    <td><strong>{{ data.nombreFormulario }}</strong></td>
                                    <td>
                                        <a href="{{ data.urlFormulario }}" class="btn btn-warning btn-lg active"
                                           role="button"
                                           aria-pressed="true" data-toggle="tooltip" data-placement="right"
                                           title="Ir al formulario"><i class="fa fa-eye"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ data.urlRespuestas }}" class="btn btn-success btn-lg active"
                                           role="button"
                                           aria-pressed="true" data-toggle="tooltip" data-placement="right"
                                           title="Ver Resultados"><i class="fa fa-table"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <button class="btn btn-outline-info btn-lg" id="BtnEditar"
                                                value="{{ data.pk }}">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                        &nbsp;
                                        <button class="btn btn-outline-danger btn-lg" id="BtnInhablitar"
                                                onclick="Inhabilitar({{ data.pk }});">
                                            <i class="fa fa-trash-o"></i>
                                        </button>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-info" role="alert">
                            Lista Vacia
                        </div>
                    {% endif %}
                    </tbody>
                </table>
            </div>
            <div class="col" id="Inhabilitados">
                <strong>Inhabilitados</strong>
                <table class="table" id="table_id">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nombre Campaña</th>
                        <th scope="col">Url Formulario</th>
                        <th scope="col">Url Resultados</th>
                        <th scope="col">Acciones</th>
                    </tr>
                    </thead>
                    <!--Registros de la tabla-->
                    <tbody id="results">
                    {% if object_list %}
                        {% for data in object_list %}
                            {% if data.estado == 0 %}
                                <tr>
                                    <td><strong>{{ data.nombreFormulario }}</strong></td>
                                    <td>
                                        <a href="{{ data.urlFormulario }}" class="btn btn-warning btn-lg active"
                                           role="button"
                                           aria-pressed="true" data-toggle="tooltip" data-placement="right"
                                           title="Ir al formulario"><i class="fa fa-eye"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ data.urlRespuestas }}" class="btn btn-success btn-lg active"
                                           role="button"
                                           aria-pressed="true" data-toggle="tooltip" data-placement="right"
                                           title="Ver Resultados"><i class="fa fa-table"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <button class="btn btn-outline-info btn-lg" id="BtnEditar"
                                                value="{{ data.pk }}">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                        &nbsp;
                                        <button class="btn btn-outline-danger btn-lg" id="BtnInhablitar"
                                                onclick="Inhabilitar({{ data.pk }});">
                                            <i class="fa fa-trash-o"></i>
                                        </button>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-info" role="alert">
                            Lista Vacia
                        </div>
                    {% endif %}
                    </tbody>
                </table>
            </div>

        </div>
        <div class="card-footer text-muted">
            <a onclick="CambioPestaña('Habilitados')" class="btn btn-success">Activos</a>
            <a onclick="CambioPestaña('Inhabilitados')" class="btn btn-info">Inactivos</a>
            <strong id="fechaActual"></strong>
        </div>
    </div>
</div>
<!--Modal Registro-->
{% include 'forms/formulario.html' %}

</body>

<script src="{% static 'scripts/jquery/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script>

    $(window).on('load', _ => {
        Ocultar();
    });


    const SuccessNotification = window.createNotification({
        theme: 'success',
        showDuration: 5000
    });
    const ErrorNotification = window.createNotification({
        theme: 'success',
        showDuration: 5000
    });


    const Ocultar = () => {
        let Habilitados = document.getElementById('Habilitados');
        let Inhabilitados = document.getElementById('Inhabilitados');


        let divisiones = [Habilitados, Inhabilitados];

        for (let i = 0; i < divisiones.length; i++) {
            divisiones[i].style.display = 'none'
        }
    };

    const CambioPestaña = (ref) => {
        Ocultar();
        let Button = document.getElementById(ref);
        Button.style.display = "block";
    };


    //Abrir modal
    $('#ButtonModal').on('click', () => {
        $('#modalForm').modal('show');
    });


    const ActualizarLista = (values) => {
        $("#table_id > tbody:last-child")
            .append(`
                               <tr>
                                <td>${values.nombreFormulario}</td>
                                <td><a href="${values.urlFormulario}" class="btn btn-warning btn-lg active" role="button" aria-pressed="true"  data-toggle="tooltip" data-placement="right" title="Ir al formulario"><i class="fa fa-eye"></a></td>
                                <td><a href="${values.urlRespuestas}" class="btn btn-success btn-lg active" role="button" aria-pressed="true"  data-toggle="tooltip" data-placement="right" title="Ver Resultados"><i class="fa fa-table"></i></a></td
                                <td>
                                <button class="btn btn-outline-info btn-lg" id="BtnEditar" value="${values.pk}">
                                    <i class="fa fa-edit"></i>
                                </button>
                                &nbsp;
                                <button class="btn btn-outline-danger btn-lg" id="BtnInhablitar" value="${values.pk}">
                                    <i class="fa fa-trash-o"></i>
                                </button>
                                 </td>
                               </tr>`);

    };

    //Formulario de registro con ajax
    $('#formulario').on('submit', function (e) {
        e.preventDefault();
        $.ajax({
            type: "POST",
            url: "{% url 'api:newForm' %}",
            data: {
                nombreFormulario: $('#nombreFormulario').val(),
                urlFormulario: $('#urlFormulario').val(),
                urlRespuestas: $('#urlRespuestas').val(),
                descripcion: $('#descripcion').val(),
                dataType: "json",
                csrfmiddlewaretoken: '{{csrf_token}}'
            },

            success: function (data) {

                let {message, error, values} = data;

                if (message) {
                    ActualizarLista(values);
                    SuccessNotification({message: 'Registro exitoso!'});
                    $('#modalForm').modal('hide');
                }
                if (error) {
                    ErrorNotification({message: error});
                }
            },
        });
    });


    const Inhabilitar = (id) => {

        $.ajax({
            url: "{% url 'api:inhabilitarFormulario' %}",
            data: {id: id, csrfmiddlewaretoken: '{{csrf_token}}'},
            dataType: 'json',
            type: "POST",
            success: (data) => {
                SuccessNotification({message: data.message})
            }
        })
    };

    const Editar = (id) => {

        $.ajax({
            url: "{% url 'api:inhabilitarFormulario' %}", data: {'id': id}, dataType: 'json',
            success: (data) => {
                SuccessNotification({message: data})
            }
        })
    };


</script>
</html>

templates/campañas.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>H&B</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/darkly/bootstrap.min.css"
          integrity="sha384-nNK9n28pDUDDgIiIqZ/MiyO3F4/9vsMtReZK39klb/MtkZI3/LtjSjlmyVPS3KdN"
          crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
{% include 'navbar/navbar.html' %}

<div class="d-flex justify-content-center mt-3 pa-5 ">
    <div class="card text-white bg-secondary mb-3" style="max-width: 50rem;">
        <div class="card-header">
            <h3>
                Campañas
            </h3>
        </div>
        <div class="card-body">
            {% if formularios_list %}
                {% for formularios in formularios_list %}
                    {% if formularios.estado %}

                        <div class="alert alert-dismissible alert-light">
                            <strong>{{ formularios.nombreFormulario }}!</strong>
                            <p class="card-text">
                                {{ formularios.descripcion }}
                            </p>
                            <a href="{{ formularios.urlFormulario }}" class="btn btn-info">
                                Ingresar al formulario
                            </a>
                        </div>

                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="alert alert-dismissible alert-primary">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Atención!</strong> Lista Vacia
                </div>
            {% endif %}

            <p class="card-text">Seleccione cualquiera de las encuestas disponibles.</p>
        </div>
    </div>
</div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</html>

templates/index.html
{% extends 'base/base.html' %}
{% block content %}
    <body>
    <div class="d-flex justify-content-center mt-3 pa-5 ">
        <div class="card text-center w-50">
            <div class="card-header">
                <strong>Iniciar Sesión</strong>
            </div>
            <div class="card-body">
                <h5 class="card-title">Habitat y Construcción</h5>
                <p class="card-text">Inicia sesión para continuar con el formulario</p>

                <div class="btn-group btn-lg">
                    <a class='btn btn-primary disabled'>
                        <i class="fa fa-facebook" style="width:16px; height:20px"></i>
                    </a>
                    <a class='btn btn-primary ' href="{% url 'social:begin' 'facebook' %}" style="width:12em">
                        Iniciar sesión con facebook
                    </a>
                </div>
                <br/><br/>

                <!--
                <button>Get External Content</button>
                <div class="btn-group btn-lg">
                    <a class='btn btn-danger disabled'>
                        <i class="fa fa-google-plus" style="width:20px; height:40px"></i>
                    </a>
                    <a class='btn btn-danger' href='{% url 'social:begin' 'google' %}' style="width:12em;">
                        Iniciar sesión con Google
                    </a>
                </div>
                <br/><br/>
                <div class="btn-group btn-lg">
                    <a class='btn btn-info disabled'>
                        <i class="fa fa-instagram" style="width:16px; height:20px"></i>
                    </a>
                    <a class='btn btn-info' href='{% url 'social:begin' 'instagram' %}' style="width:12em">
                        Iniciar sesión con Instagram
                    </a>
                </div>
            -->
            </div>
            <div class="card-footer text-muted">
                <strong id="fechaActual"></strong>
            </div>
        </div>
    </div>
    </body>
{% endblock %}

templates/login.html
{% extends 'base/base.html' %}
{% block content %}
    <body>
    <div class="d-flex justify-content-center mt-3 pa-5 ">
        <div class="card text-center w-50">
            <div class="card-header">
                <strong>Iniciar Sesión</strong>
            </div>
            <div class="card-body">
                <h5 class="card-title">Habitat y Construcción</h5>
                <p class="card-text">Administrador</p>
                <form action="{% url 'api:login' %}" method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Nombre usuario" name="username" value=""/>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="Contraseña" name="password" value=""/>
                    </div>

                    <Button class="btn btn-success" type="submit">Ingresar</Button>

                </form>
            </div>
            <div class="card-footer text-muted">
                <strong id="fechaActual"></strong>
            </div>
        </div>
    </div>
    </body>
{% endblock %}